name: twitter-automation

on:
  schedule:
    - cron: '0 */3 * * *'
  #push:
  #  branches:
  #    - main
jobs:
  bigbookofr_bot-post:
    runs-on: macOS-latest
    
    steps:
      - uses: actions/checkout@main
      - uses: r-lib/actions/setup-r@v2
      - name: Install tidyverse package
        run: Rscript -e 'install.packages("tidyverse", dependencies = TRUE)'
      - name: Install rtweet package
        run: Rscript -e 'install.packages("rtweet", dependencies = TRUE)'
      - name: Install lubridate package
        run: Rscript -e 'install.packages("lubridate", dependencies = TRUE)'
      - name: Get Tweets
        run: Rscript tweets_collection.R
        env:
          RBOT_TWITTER_CONSUMER_API_KEY: ${{ secrets.RBOT_TWITTER_CONSUMER_API_KEY }}
          RBOT_TWITTER_CONSUMER_API_SECRET: ${{ secrets.RBOT_TWITTER_CONSUMER_API_SECRET }}
          RBOT_TWITTER_ACCESS_TOKEN: ${{ secrets.RBOT_TWITTER_ACCESS_TOKEN }}
          RBOT_TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.RBOT_TWITTER_ACCESS_TOKEN_SECRET }}
